language: node_js
sudo: false
cache: yarn
node_js:
  - "node"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "iojs"
  - "0.12"
  - "0.10"

matrix:
  allow_failures:
    - node_js: "iojs"
    - node_js: "0.12"
    - node_js: "0.10"

notifications:
  email: false
